### ISSUE TITLE
are these supposed to work standalone in 40/41?

### ISSUE THREAD

**Issue by mackenza** [Brackets-Themes/Zamiere#1]
Hi @MiguelCastillo , are these new standalone themes from the extension manager supposed to work without your Themes extension in Sprint 40 (actually I am running of dev master so it's actually 40/41)?

**Comment by MiguelCastillo** [comment]
@mackenza These themes will work without my theme extension when we release the theme feature in brackets core, which we are trying to do for sprint 41.

You can still use them with my theme extension if you really wanted, but they are already shipped with my theme extension.  In order to use them with my theme extension, you will need to rename main.less to something more meaningful like zamiere.less, and place in the theme directory in the theme extension.  It should work then.

**Comment by MiguelCastillo** [comment]
@mackenza Let me take a step back.  The reason these themes are showing up in the extension registry is because I am

1 Making sure the workflow for installing themes from the registry works
2 Making a few proper extra theme options available for people when the theme in brackets lands.

If you want to test the functionality, you can use my brackets branch 
https://github.com/MiguelCastillo/brackets

If you want to track the pull request, take a look here
https://github.com/adobe/brackets/pull/7616

**Comment by mackenza** [comment]
ok I understand now.  I am using your branch on Linux to test these out.

Is the structure of the `main.less` file solid now?  I may try and convert `railcasts` if it is, as it's the theme I use all the time from your extension.

**Comment by MiguelCastillo** [comment]
@mackenza So, the structure of zamiere/main.less is exactly the same as it was before. As a matter of fact, already existing themes will continue to work.  What you will need is just a package.json so that the extension loader can pick it up.  The important part in the package.json is the theme field, which has to point to the theme file.  The theme file itself can be less or css.

What we are working is actually a bit more than just loading theme files though.  We are allowing themes to inherit the stuff that Brackets provides.  Take a look at https://github.com/Brackets-Themes/EasyDark/blob/master/main.less so that you can see it.  Allowing less mixins with stuff Brackets provides will allow theme authors to easily extend things like a dark theme, or a light theme...

Any feedback would be greatly appreciated :)

-mc

**Comment by MiguelCastillo** [comment]
@mackenza Should I expect you as a contributor in the Brackets-Themes group?? :D

**Comment by mackenza** [comment]
@MiguelCastillo lol, I will do my best.  I am not the best CSS guy out there, but I do have an interest in the whole Brackets theming thing.

**Comment by MiguelCastillo** [comment]
@mackenza Exactly why you need to help!  Because you are interested.  I will help you :)    I already added you as a contributor to the Brackets-Themes group, so you should be able to create your Ralicast theme repo and contribute to the community :)

**Comment by mackenza** [comment]
@MiguelCastillo I tried just now but it says I don't have repo create perms for the org

**Comment by MiguelCastillo** [comment]
@mackenza Sorry dude, try now.

**Comment by MiguelCastillo** [comment]
@mackenza Sweet!  This is nice because now you can add screenshots and stuff :)  I want to put together some instructions.
